### ISSUE TITLE
SSL Handshake Error when uploading reports

### ISSUE THREAD

**Issue by leofischer** [codacy/codacy-coverage-reporter#142] opened 2019-11-21 18:30 UTC
### Are you looking for help?

We are getting an ssl handshake error when uploading the coverage reports.

<img width="1230" alt="Screen Shot 2019-11-21 at 12 09 08" src="https://user-images.githubusercontent.com/148611/69365575-44dac780-0c5a-11ea-9b04-3550ef114dc2.png">

### Scala Version (2.10.x / etc)

2.12.7

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Linux bionic_84d22b9c-9b05-476c-a4da-6f304f74724c_40e2d74f09c2 4.15.0-1052-aws #54-Ubuntu SMP Tue Oct 1 15:43:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

### Library Dependencies

We generate coverage with .NetCore 2.2 using Coverlet, but these simply generates a cobertura file, so we are not adding any dependencies for the Coverage Reporter.

### Expected Behavior

Files upload correctly

### Actual Behavior

We get an SSL Handshake Error.

E.g.

```
2019-11-20 19:39:43,773 INFO             com.codacy Using API base URL: https://api.codacy.com 
2019-11-20 19:39:43,773 INFO             com.codacy Parsing coverage data from: /home/rof/src/github.com/conekta/Conekta.Orchestrator.Core/unit_tests.cobertura.xml ... 
2019-11-20 19:39:44,192 INFO             com.codacy Generated report: /home/rof/src/github.com/conekta/Conekta.Orchestrator.Core/codacy-coverage.json (69.72 kB) 
2019-11-20 19:39:44,192 INFO             com.codacy Uploading coverage data... 
Exception in thread "main" javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2020)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1127)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(AbstractDelegateHttpsURLConnection.java:100)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(AbstractDelegateHttpsURLConnection.java:80)
	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:705)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1585)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at scalaj.http.HttpRequest.scalaj$http$HttpRequest$$doConnection(Http.scala:367)
	at scalaj.http.HttpRequest.exec(Http.scala:343)
	at scalaj.http.HttpRequest.asString(Http.scala:491)
	at com.codacy.api.client.CodacyClient.post(CodacyClient.scala:72)
	at com.codacy.api.service.CoverageServices.sendReport(CoverageServices.scala:20)
	at com.codacy.rules.ReportRules$$anonfun$coverageWithTokenAndCommit$1$$anonfun$apply$2.apply(ReportRules.scala:62)
	at com.codacy.rules.ReportRules$$anonfun$coverageWithTokenAndCommit$1$$anonfun$apply$2.apply(ReportRules.scala:47)
	at cats.syntax.EitherOps$.flatMap$extension(either.scala:148)
	at com.codacy.rules.ReportRules$$anonfun$coverageWithTokenAndCommit$1.apply(ReportRules.scala:47)
	at com.codacy.rules.ReportRules$$anonfun$coverageWithTokenAndCommit$1.apply(ReportRules.scala:40)
	at cats.syntax.EitherOps$.flatMap$extension(either.scala:148)
	at com.codacy.rules.ReportRules.withCommitUUID(ReportRules.scala:124)
	at com.codacy.rules.ReportRules.coverageWithTokenAndCommit(ReportRules.scala:40)
	at com.codacy.rules.ReportRules.codacyCoverage(ReportRules.scala:30)
	at com.codacy.CodacyCoverageReporter$.run(CodacyCoverageReporter.scala:22)
	at com.codacy.configuration.parser.ConfigurationParsingApp.run(ConfigurationParser.scala:13)
	at com.codacy.configuration.parser.ConfigurationParsingApp.run(ConfigurationParser.scala:11)
	at caseapp.CommandAppWithPreCommand$$anonfun$main$1.apply(CommandAppWithPreCommand.scala:97)
	at caseapp.CommandAppWithPreCommand$$anonfun$main$1.apply(CommandAppWithPreCommand.scala:82)
	at scala.Option.foreach(Option.scala:257)
	at caseapp.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:82)
	at com.codacy.CodacyCoverageReporter.main(CodacyCoverageReporter.scala)
```

### Reproducible Test Case

```bash
#Install codacy coverage
curl -Ls -o codacy-coverage-reporter "$(curl -Ls https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | contains("codacy-coverage-reporter-linux"))) | .[0].browser_download_url')"
chmod +x codacy-coverage-reporter
dotnet test tests/YourService.UnitTests/ /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(pwd)/unit_tests /p:Exclude="[xunit*]"
sbt scalaVersion
uname -a
java -version
./codacy-coverage-reporter report -l CSharp -r unit_tests.cobertura.xml
```

**Comment by leofischer** [comment] 2019-11-21 18:31
Any thoughts @ljmf00?

**Comment by mrfyda** [comment] 2019-11-21 20:42
@leofischer can you try using the assembly jar instead of the binary version?

Using:
```
curl -Ls -o codacy-coverage-reporter-assembly.jar $(curl -Ls https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({content_type, browser_download_url} | select(.content_type | contains("java-archive"))) | .[0].browser_download_url')
java -jar codacy-coverage-reporter-assembly.jar report -l Java -r jacoco.xml
```
https://github.com/codacy/codacy-coverage-reporter#github-1

We're investigating an issue regarding a new certificate and the published binary version.

**Comment by fasatrix** [comment] 2019-11-25 02:57
> @leofischer can you try using the assembly jar instead of the binary version?
> 
> Using:
> 
> ```
> curl -Ls -o codacy-coverage-reporter-assembly.jar $(curl -Ls https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({content_type, browser_download_url} | select(.content_type | contains("java-archive"))) | .[0].browser_download_url')
> java -jar codacy-coverage-reporter-assembly.jar report -l Java -r jacoco.xml
> ```
> 
> https://github.com/codacy/codacy-coverage-reporter#github-1
> 
> We're investigating an issue regarding a new certificate and the published binary version.

Hi @mrfyda, this workaround has work for me as well however we would like a full solution using the binary as well.. Can you please consider reopening this issue? Thanks

**Comment by fasatrix** [comment] 2019-11-25 02:58
> @leofischer can you try using the assembly jar instead of the binary version?
> 
> Using:
> 
> ```
> curl -Ls -o codacy-coverage-reporter-assembly.jar $(curl -Ls https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({content_type, browser_download_url} | select(.content_type | contains("java-archive"))) | .[0].browser_download_url')
> java -jar codacy-coverage-reporter-assembly.jar report -l Java -r jacoco.xml
> ```
> 
> https://github.com/codacy/codacy-coverage-reporter#github-1
> 
> We're investigating an issue regarding a new certificate and the published binary version.

Hi @mrfyda, this workaround has work for me as well however we would like a full solution using the binary as well.. Can you please consider reopening this issue? Thanks

**Comment by mrfyda** [comment] 2019-11-25 09:50
Yes.
We will recompile the binary version and make it available as soon as possible.

**Comment by keyotik** [comment] 2019-11-25 22:47
Hi, we just tried downloading the newest assembly jar and we found out that the content-type was changed to application/octet-stream instead of application/java-archive. This is making our scripts to fail. Is this a new change to carried forward?

**Comment by fasatrix** [comment] 2019-11-25 23:03
Hi @mrfyda, this "select(.name | endswith(".jar")))" is not reflected in your documentation... your documentation is still referring to select(.content_type | contains("java-archive") (GitHub section)

Are you planning on more breaking changes?? I guess it will be good to know as this is nearly happening everyday and might raise frustration significantly.

**Comment by tylerkron** [comment] 2019-11-27 02:26
This is breaking our CI pipeline in `bitbucket pipelines`.  Basically can't use code coverage until this is fixed.

**Comment by andreaTP** [comment] 2019-11-27 15:23
This should be fixed with the latest binary just published.
Version is `6.1.3` and please note the comment on the workaround in #146 

@tylerkron @leofischer @fasatrix 
can you please confirm that the issue is fixed?

Sorry for the trouble and thanks for the feedback!

**Closed** 2019-11-27 16:27 UTC
Labels: bug
