### ISSUE TITLE
curl: (3) <url> malformed

### ISSUE THREAD

**Issue by Jeehut** [codacy/codacy-coverage-reporter#185] opened 2020-03-25 08:54 UTC
I'm getting an error when I run this on Bitrise CI:

```bash
bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.lcov
```

I have also tried the wget variant, resulting in the same issue:

```bash
bash <(wget -q -O - https://coverage.codacy.com/get.sh) report -r coverage.lcov
```

See the logs on [this Bitrise build](https://app.bitrise.io/build/ffc95556659f6572#?tab=log).

**Comment by lolgab** [comment] 2020-03-25 09:34
Could be that Bitrise is using an old curl version?

**Comment by lolgab** [comment] 2020-03-25 09:36
Can you ssh and print the version? You can either try to upgrade the CI image or the curl version.

**Comment by lolgab** [comment] 2020-03-25 09:56
You can even try with:
```bash
curl -Ls https://coverage.codacy.com/get.sh | bash -s report -r coverage.lcov
```
or
```bash
curl -Ls https://coverage.codacy.com/get.sh | sh -s report -r coverage.lcov
```
The problem is that we require `java` on non-linux machines.

**Comment by mrfyda** [comment] 2020-03-25 11:30
> {
  "message": "API rate limit exceeded for 207.254.0.250. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}

when doing a curl to github to get the latest version of the jar I get that message while ssh into bitrise

**Comment by Jeehut** [comment] 2020-03-25 13:02
@lolgab Here's the output of `curl --version` on Bitrise:
```
curl 7.54.0 (x86_64-apple-darwin18.0) libcurl/7.54.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy 
```

**Comment by Jeehut** [comment] 2020-03-25 13:53
@lolgab I just installed the latest `curl` version via Homebrew on the CI and used that instead. Same issue. The used curl version:

```
curl 7.69.1 (x86_64-apple-darwin18.7.0) libcurl/7.69.1 SecureTransport zlib/1.2.11
Release-Date: 2020-03-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
```

**Comment by andreaTP** [comment] 2020-03-26 20:51
@Jeehut first of all, thanks a lot for your interest and for reporting this bug!

Here we have two problems indeed:
 - GH is rate limiting from Bitrise -> solved in https://github.com/codacy/codacy-coverage-reporter/pull/189
 - We are not currently publishing a binary executor for Darwin -> solved in https://github.com/codacy/codacy-coverage-reporter/pull/186

Here I ask you a little effort from you in testing this WIP version so that we don't merge something that is evidently not working (sorry I have limited experience with Darwin builds):
```bash
mkdir -p .codacy-coverage
curl -LS -o .codacy-coverage/codacy-coverage-reporter https://dl.bintray.com/codacy/Binaries/7.6.5-buildonosx.20ef954/codacy-coverage-reporter-darwin
bash <(curl -Ls https://raw.githubusercontent.com/codacy/codacy-coverage-reporter/20ef954686493a4b6790e3bdad6eb1f5bd532d17/get.sh) report -r coverage.lcov
```
If it works, you should be able to use this workaround until we merge everything to master.

**Comment by Jeehut** [comment] 2020-03-27 07:53
@andreaTP No worries, I'm happy to test it out and I just did. As you can see [here](https://app.bitrise.io/build/b8db825caef22bd8#?tab=log) it is now working with the exact code you posted above! Looks like the two branches are working as expected. 👍 💯

**Comment by andreaTP** [comment] 2020-04-07 09:37
@Jeehut thanks for your patience! I'm happy to announce that we merged and published everything, starting from now(version `7.7.0`) you are going to be able to use the default upstream scripts and binaries.
Please feel free to file a new issue if you hit any problem!

**Closed by andreaTP** 2020-04-07 09:37 UTC
Labels: bug

**Comment by Jeehut** [comment] 2020-04-07 10:04
@andreaTP Thank you very much, I reset the code to the default script and it works now as you can see [here](https://app.bitrise.io/build/3972b23178403dd2#?tab=log). 🎉

**Comment by andreaTP** [comment] 2020-04-07 11:20
Indeed thanks a lot for the feedback @Jeehut !
