### ISSUE TITLE
Java.net.UnknownHostException on alpine

### ISSUE THREAD

**Issue by micbar** [codacy/codacy-coverage-reporter#212] opened 2020-05-14 10:15 UTC
### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

- Running on alpine 3.11 in a drone.io pipeline

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Run `wget -qO - https://coverage.codacy.com/get.sh | bash -s report -l Javascript`
2. Coverage should be uploaded
3.

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.
```
+ wget -qO - https://coverage.codacy.com/get.sh | sh -s report -l Javascript -r coverage/lcov.info
     ______          __
    / ____/___  ____/ /___ ________  __
   / /   / __ \/ __  / __ `/ ___/ / / /
  / /___/ /_/ / /_/ / /_/ / /__/ /_/ /
  \____/\____/\__,_/\__,_/\___/\__, /
                              /____/

  Codacy Coverage Reporter

 [0;36m--> [0;90mDownload the codacy reporter codacy-coverage-reporter-linux... (latest)[0m
#=#=#                                                                         
##O#- #                                                                       
##O=#  #                                                                      

######################################################################## 100.0%
#=#=#                                                                         
##O#- #                                                                       
##O=#  #                                                                      

                                                                           0.2%
                                                                           0.6%
                                                                           1.3%
##                                                                         2.9%
####                                                                       6.0%
########                                                                  11.8%
#################                                                         24.2%
##################################                                        48.5%
#####################################################################     97.0%
######################################################################## 100.0%
2020-05-13 21:43:24,080 INFO             com.codacy API base URL: https://api.codacy.com 
2020-05-13 21:43:24,081 INFO             com.codacy Can't find any provider. 
2020-05-13 21:43:24,081 INFO             com.codacy Trying to get commit from git 
2020-05-13 21:43:24,093 INFO             com.codacy Commit UUID not provided, using latest commit of current directory:
2551e21551676b8345e10ae42b8135a86be78543 Lukas Hirt <lukashirt@mail.com> Wed May 13 21:38:07 GMT 2020 
2020-05-13 21:43:24,093 INFO             com.codacy Parsing coverage data from: /drone/src/coverage/lcov.info ... 
2020-05-13 21:43:24,098 INFO             com.codacy Generated report: /drone/src/coverage/codacy-coverage.json (6.64 kB) 
2020-05-13 21:43:24,099 INFO             com.codacy Uploading coverage data... 
Exception in thread "main" java.net.UnknownHostException: api.codacy.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
	at scalaj.http.HttpRequest.doConnection(Http.scala:367)
	at scalaj.http.HttpRequest.exec(Http.scala:343)
	at scalaj.http.HttpRequest.asString(Http.scala:491)
	at com.codacy.api.client.CodacyClient.post(CodacyClient.scala:74)
	at com.codacy.api.service.CoverageServices.postRequest(CoverageServices.scala:91)
	at com.codacy.api.service.CoverageServices.sendReport(CoverageServices.scala:27)
	at com.codacy.rules.ReportRules.sendReport(ReportRules.scala:128)
	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$8(ReportRules.scala:54)
	at scala.util.Either.flatMap(Either.scala:341)
	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$7(ReportRules.scala:53)
	at scala.util.Either.flatMap(Either.scala:341)
	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$6(ReportRules.scala:52)
	at scala.util.Either.flatMap(Either.scala:341)
	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$4(ReportRules.scala:51)
	at scala.util.Either.flatMap(Either.scala:341)
	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$3(ReportRules.scala:50)
	at scala.collection.immutable.List.map(List.scala:286)
	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$2(ReportRules.scala:47)
	at scala.util.Either.flatMap(Either.scala:341)
	at com.codacy.rules.ReportRules.$anonfun$codacyCoverage$1(ReportRules.scala:40)
	at com.codacy.rules.ReportRules.$anonfun$withCommitUUID$4(ReportRules.scala:267)
	at com.codacy.rules.ReportRules.$anonfun$withCommitUUID$4$adapted(ReportRules.scala:267)
	at scala.util.Either.flatMap(Either.scala:341)
	at com.codacy.rules.ReportRules.withCommitUUID(ReportRules.scala:267)
	at com.codacy.rules.ReportRules.codacyCoverage(ReportRules.scala:35)
	at com.codacy.CodacyCoverageReporter$.$anonfun$sendReport$1(CodacyCoverageReporter.scala:41)
	at scala.util.Either.flatMap(Either.scala:341)
	at com.codacy.CodacyCoverageReporter$.sendReport(CodacyCoverageReporter.scala:33)
	at com.codacy.CodacyCoverageReporter$.run(CodacyCoverageReporter.scala:18)
	at com.codacy.configuration.parser.ConfigurationParsingApp.run(ConfigurationParser.scala:13)
	at com.codacy.configuration.parser.ConfigurationParsingApp.run(ConfigurationParser.scala:11)
	at caseapp.CommandAppWithPreCommand.$anonfun$main$1(CommandAppWithPreCommand.scala:97)
	at caseapp.CommandAppWithPreCommand.$anonfun$main$1$adapted(CommandAppWithPreCommand.scala:82)
	at scala.Option.foreach(Option.scala:407)
	at caseapp.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:82)
	at com.codacy.CodacyCoverageReporter.main(CodacyCoverageReporter.scala)

 [0;31m--> [0;90mFailed![0m
```
Running the script on an ubuntu container works fine.

**Comment by LukasHirt** [comment] 2020-05-14 11:08
Same happens when running the script in virtual box running alpine following this [setup instructions](https://wiki.alpinelinux.org/wiki/Install_Alpine_on_VirtualBox).

Tried also to run `echo "$(dig +short api.codacy.com | tail -n1) api.codacy.com" >> /etc/hosts` before sending the coverage but that didn't help.

**Comment by josemiguelmelo** [comment] 2020-05-14 16:10
Hi @micbar 🙂

Coverage reporter binary is incorrectly linked to `glibc` and we are currently working to find a solution to solve it.

While we don't find a solution, installing `glibc` on alpine should solve the issue.

Thanks,

**Comment by micbar** [comment] 2020-05-14 18:36
Thanks @josemiguelmelo 

We will add that to our alpine container in the CI

**Comment by andreaTP** [comment] 2020-05-15 11:20
Thanks a lot for the bug report.
I took the chance to go down the rabbit hole and the root cause of this problem is:
https://github.com/oracle/graal/issues/2146

and we have a POC workaround in #214 

Hopefully we will be able to release a version that removes this limitation soon.

**Comment by josemiguelmelo** [comment] 2020-05-18 15:26
The issue should have been fixed by https://github.com/codacy/codacy-coverage-reporter/pull/214 and the `glibc` workaround should not be needed on the new version that was released (https://github.com/codacy/codacy-coverage-reporter/tree/9.0.0).

Thanks a lot for reporting the bug.

**Closed by josemiguelmelo** 2020-05-18 15:26 UTC
